### ISSUE TITLE
Memory corruption caused by calling ctx.getPostParams("username")

### ISSUE THREAD

**Issue by teroz** [planety/prologue#10]
Good work on this project I like its direction. I'm running the blog example and I get a memory corruption after successfully logging in. Offending code is in 21 of base.nim 

```nim
let username = ctx.getPostParams("username")
```

![Memory corruption](https://user-images.githubusercontent.com/853846/79689726-f0626500-8256-11ea-9203-05e1931a6385.png)

**Comment by xflywind** [comment]
What's your Nim version?
Maybe disable --gc:arc in config.nims.

**Comment by teroz** [comment]
Nim version is 1.2
OS: `Linux badger.lan 5.6.4 #1 SMP PREEMPT Fri Apr 17 15:04:52 SAST 2020  x86_64 GNU/Linux`
App doesn't throw any error. It keeps running but unable to service any other requests.

I tried it with with the disabled --gc:arc and that works fine

**Comment by xflywind** [comment]
Arc is still Immature and is leaking memory with `async`. Maybe just use default gc. 
https://forum.nim-lang.org/t/5734

**Comment by teroz** [comment]
Awesome will do :+1:
