### ISSUE TITLE
Port number not working

### ISSUE THREAD

**Issue by GabrielLasso** [planety/prologue#102]
I am running a server on 8888 and trying to get the port number from ctx.request.port, but it is getting me an empty string.

**Comment by ringabout** [comment]
IMO You should use `ctx.gScope.settings.port` to get the port number.
https://planety.github.io/prologue/coreapi/context.html#GlobalScope

**Comment by GabrielLasso** [comment]
> IMO You should use `ctx.gScope.settings.port` to get the port number.
> https://planety.github.io/prologue/coreapi/context.html#GlobalScope

Thanks, I'll try
