### ISSUE TITLE
Allow multiple servers running in parallel in async mode

### ISSUE THREAD

**Issue by mildred** [planety/prologue#105]
It would be great if there was the possibility to run multiple http servers in parallel (I need one for an admin interface and another for an access API listening on a different port and IP).

It would be nice if there was a `run_async(): Future[void]` function. You could run multiple servers in parallel and then `runForever()` to do the main loop.

**Comment by ringabout** [comment]
With `asynchttpserver` backend, it's easy to run multiple servers in parallel. But `httpx` backend uses one event loop(blocking), it's hard to implement this.
