### ISSUE TITLE
"different lengths for slice assignment" with session middleware

### ISSUE THREAD

**Issue by ITwrx** [planety/prologue#107]
trying to figure out how to use redis session middleware and flash messages from the docs, but i get the above error upon page load, when adding the session middleware via the app.use line at the bottom. Happens with nim 1.2.8, 1.4.0, and 1.4.2.

i have:
`import prologue/middlewares/sessions/redissession`

```
let settings = newSettings()
var app = newApp(settings)
app.use(sessionMiddleware(settings))
```

**Comment by ringabout** [comment]
The codes above works for me in Linux with prologe@0.4.2 

Are there the minimal codes to reproduce these issues? 
What's your OS?

**Comment by ITwrx** [comment]
hmm, i guess i should have tried in a clean slate project first. 
Let me try that and get back to you. It may be tomorrow though. 
fedora 32.
thanks

**Comment by ringabout** [comment]
You could also ask in discord server too.
https://discord.gg/BuaNCEQ9

**Comment by ITwrx** [comment]
i'm just going to close this for now, as i have already implemented a workaround for the app i was building. I will revisit if/when i try to build something more substantial, or get tired of looking at my workaround.

BTW, thanks for the discord offer, but i don't want to use a proprietary application (or server) if i can help it. Github is a grandfathered exemption that i hope to wean myself from. I also don't like the idea of posts not sticking around in a public place so people aren't having to ask the same questions over and over again. 

It would be nice if Prologue had a freedom and privacy-respecting support forum or chat application, or if the nimlang forum had notification features. Finally, I prefer for things to be documented so well i don't have to bother people with my problems in the first place.
