### ISSUE TITLE
[Question] How to send headers with custom response?

### ISSUE THREAD

**Issue by ITwrx** [planety/prologue#108]
i'm trying to test SSE (Server Sent Events), but i'm having trouble with Prologue's ctx, headers and response. I don't know if there's  a bug, or maybe an FR for an improvement to the docs, or maybe an SSE example.

Example 1
```
#sends response with code and data, but not custom headers. 
  ctx.handled = true  
  ctx.response.setHeader("Content-Type", "text/event-stream")
  ctx.response.setHeader("Cache-Control", "no-cache")  
  let data = "data: some cool data, man!"
  await ctx.respond(Http200, data)

```
Example 2
  ```
#sends custom headers, but not data
  ctx.handled = true  
  ctx.response.setHeader("Content-Type", "text/event-stream")
  ctx.response.setHeader("Cache-Control", "no-cache")
  let data = "data: some cool data, man!"
  #just trying to force it to send my headers, which works, but doesn't include my data...
  await ctx.respond()
```
I thought using setHeader() would add the headers to the ctx for me, and it does b/c i can echo after setting, but they don't get sent with the response when calling ctx.respond in example 1. 

How to send the headers with the response (with my data) to override the default "text/plain" header type so SSE will work?

thanks

**Comment by bung87** [comment]
when call ctx.respond add `headers = ctx.response.headers` param , thought it just use internal, generally you will use `newHttpHeaders()`

**Comment by ITwrx** [comment]
Thanks for your response.

I did:

  ```
ctx.handled = true  
  ctx.response.setHeader("Content-Type", "text/event-stream")
  ctx.response.setHeader("Cache-Control", "no-cache")  
  let data = "data: some cool data, man!"
  await ctx.respond(Http200, data, headers = ctx.response.headers)
```
and now it sends the headers, but not the data...

i also tried (similar to the asynchttpserver docs):

 ```
  let headers = {"Cache-Control": "no-cache", "Content-type": "text/event-stream"}
  ctx.handled = true  
  let data = "data: some cool data, man!"
  await ctx.respond(Http200, data, headers.newHttpHeaders())
```
but i got a type mismatch between the HttpHeaders type i tried to use, and the ResponseHeaders type Prologue is expecting.

**Comment by ringabout** [comment]
see
https://planety.github.io/prologue/coreapi/beast/request.html#respond%2CRequest%2CHttpCode%2Cstring%2CResponseHeaders

```nim
 let headers = {"Cache-Control": "no-cache", "Content-type": "text/event-stream"}
 ctx.handled = true  
 let data = "data: some cool data, man!"
 await ctx.respond(Http200, data, headers.initResponseHeaders())
```

**Comment by ITwrx** [comment]
@xflywind thanks, but that still doesn't send the data. I'm inspecting in FF+Chromium dev tools.
status code and headers, yes. data, no.

thanks for the reference to the code. i had tried newResponseHeaders(), but no such proc existed. :)

**Comment by ringabout** [comment]
You need to set the `contentLength` of body
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length

`ctx.setHeader("Content-length", $data.len)`

**Comment by ITwrx** [comment]
Thanks. I did that, but it still doesn't send the data. 
  ```
  ctx.handled = true  
  let data = "data: some cool data, man!"
  let headers = {"Cache-Control": "no-cache", "Content-type": "text/event-stream", "Content-length": $data.len}
  await ctx.respond(Http200, data, headers.initResponseHeaders())
```

also, i notice that the content-length is shown correctly in the response even if i don't set it manually in the header, as above.

**Comment by ringabout** [comment]
It works for `staticFileResponse` with normal response

https://github.com/planety/prologue/blob/5774bde9fda7a67dfb1d6b2996a87cc4fed1da14/src/prologue/core/context.nim#L519

I'm not sure about "text/event-stream".

**Comment by ITwrx** [comment]
It was my fault after we got the headers working. The spec requires that the data is terminated by new lines. I didn't realize those were mandatory. The below works.

  ```
ctx.handled = true  
  let data = "data: some cool data, man!\n\n"
  let headers = {"Cache-Control": "no-cache", "Content-type": "text/event-stream", "Connection": "keep-alive"}
  await ctx.respond(Http200, data, headers.initResponseHeaders())
```

Thanks a lot for the help. I will submit a full example soon so it can be documented. People have asked about this on the nim-lang forum, but it's never been answered successfully, that i've seen. Web sockets are not always the best choice for everything.

**Comment by ITwrx** [comment]
well, i may wait to provide an example until i have a more real world example(s) to provide. There's nothing more frustrating than examples that are so simple you still can't figure out how to do the real world thing you're trying to do. My current implementation was just enough to get some data on the page.
