### ISSUE TITLE
Web frameworks benchmark

### ISSUE THREAD

**Issue by waghanza** [planety/prologue#11]
Hi @planety,

Do you want to add `prologue` in https://github.com/the-benchmarker/web-frameworks. 

The purpose of this benchmark is to compare frameworks on a simple (an homogeneous) way.

We have already :

+ `jester`
+ `httpbeast`

Wdyt ?

Regards,

**Comment by xflywind** [comment]
It sounds interesting. What should I do?

**Comment by xflywind** [comment]
Now `prologue` is based on `httpbeast`, I may change it to `netkit`. Maybe it is more interesting to bench `netkit`.
https://github.com/iocrate/netkit

**Comment by waghanza** [comment]
> What should I do?

Just create a `PR`, the requirements is to have 3 endpoints 

+ GET / 
+ POST /user
+ GET /user/:id

The purpose is to test `frameworks`, but by the way, benchmarking `netkit` could be great

**Comment by xflywind** [comment]
Thanks, I will do it when I have time.
