### ISSUE TITLE
More verbose error logging on 500 error

### ISSUE THREAD

**Issue by daehee** [planety/prologue#114]
What would be the best way to include a more verbose dump of context for 500 errors? i.e. Context details of the client request including path and query parameters; full stack trace would be even better.

## Current environment

Initializing the app with this startup event:
```
proc setLoggingLevel() =
  addHandler(newConsoleLogger())
  logging.setLogFilter(lvlAll)

let loggerEvent = initEvent(setLoggingLevel)
var app = newApp(settings = settings, startup = @[loggerEvent])
```

## Example log

This is the only error data for the request/response included in the logs, which makes it difficult to debug and reproduce:
```
stdbuf[139540]: DEBUG GET
stdbuf[139540]: ERROR index out of bounds, the container is empty
stdbuf[139540]: DEBUG 500 Internal Server Error {"content-type": @["text/html; charset=UTF-8"]}
```

**Comment by ringabout** [comment]
It should have asynctrace. Is it?

![image](https://user-images.githubusercontent.com/43030857/107303215-9ec2e980-6ab9-11eb-9de1-2531054adc0a.png)

**Comment by daehee** [comment]
The app is compiled with  `--define:release` &   `--define:usestd`, so not using default `httpx` module. I'm guessing this is why my output is different.

**Comment by ringabout** [comment]
`-d:usestd` is fine.
traceback won't show with release mode.

```nim
var x: seq[int]
let i = 100
echo x[i]
```
![image](https://user-images.githubusercontent.com/43030857/107307991-c23e6200-6ac2-11eb-9666-f50cfab4114a.png)

With debug build, you should have the full traceback.

**Comment by daehee** [comment]
Ok thanks!
