### ISSUE TITLE
CORS preflight failing with  an `errorMsg` of "method"

### ISSUE THREAD

**Issue by zr0z** [planety/prologue#122]
When using the built-in CORS middleware, the Preflight on `OPTIONS` fails with an `errorMsg` with a value of `"method"`.

https://github.com/planety/prologue/blob/82ff8f4bbf23083f49aa04bb1b06a817e9d33d37/src/prologue/middlewares/cors.nim#L119-L120

In the middleware, the `allowMethodsSeq` is a `seq` of strings that have been lower-cased using the `toLowerAscii` proc, while browsers are usually sending the `Access-Control-Request-Method` in uppercase, causing the condition to fail.

https://github.com/planety/prologue/blob/82ff8f4bbf23083f49aa04bb1b06a817e9d33d37/src/prologue/middlewares/cors.nim#L80-L83

The fix is to use `toLowerAscii` when getting the `Access-Control-Request-Method` header so from:

https://github.com/planety/prologue/blob/82ff8f4bbf23083f49aa04bb1b06a817e9d33d37/src/prologue/middlewares/cors.nim#L93-L94

to :

```nim
let
    accessControlRequestMethod = toLowerAscii(reqHeaders["Access-Control-Request-Method"])
```

I can submit a PR if needed.

Thank you for this framework!

### Versions used
```
Nim: 1.4.8
Prologue: 0.4.4 
```

**Comment by bung87** [comment]
confirmed, should fix as described.

**Comment by ringabout** [comment]
Hi, nice catch. PR is welcome.

**Comment by zr0z** [comment]
Closing the issue since PR has been merged
