### ISSUE TITLE
How to serve static folder at specific route?

### ISSUE THREAD

**Issue by ericarthurc** [planety/prologue#126]
My folder setup is:
```
root
│   project.nimble  
│
└───src
│   │   main.nim
│   │   ...etc...
│   
└───static
    │   sw.js
    │   manifest.json
    │   robots.txt
    └───js
    │  │   random.js
    │
    └───css
       │   main.css
```

And I am using `app.use(staticFileMiddleware("static"))` to serve this static folder, but this on the server serves at "localhost:port/static/" not "localhost:port/"

I need to serve sw.js, mainfest.json and robots.txt at root "/"

Is there a way to direct this entire static folder to serve at "/" root? Not the folder name?
Thanks!

Sidenote, I did see the redirect for a single file, but was looking to "redirect" this entire static folder to root path "/", thanks!

Amazing work!

**Comment by ringabout** [comment]
Not yet. But you can implement your own version of staticFileMiddleware.

https://github.com/planety/prologue/blob/devel/src/prologue/middlewares/staticfile.nim

Or create a helper proc for redirect directory.
```
proc redirectDir (dir: string) =
  Walk the dir:
     Redirect the file
```
