### ISSUE TITLE
Custom Error Pages

### ISSUE THREAD

**Issue by TokenChingy** [planety/prologue#13]
First of all, this framework is pretty dope. I'm looking through the source code and I've come across the `pages.nim`for handling 404's, 500's etc. What's the best method to override these pages and build custom ones for my own purposes — without altering the library?

**Comment by xflywind** [comment]
You can register error handler for building a custom pages.
https://github.com/planety/prologue/blob/a4b6ed77fbdf0bb367eb3e1367daa6155aea36ef/tests/test_function/t_application.nim#L29
