### ISSUE TITLE
In android termux prologue does not compile because of an error in httpx

### ISSUE THREAD

**Issue by sk-Prime** [planety/prologue#130]
I wanted to make a simple android tool. As a test I made a `test.nim` file which contains `import prologue` but it does not compile because of the httpx.nim

#### Error
`httpx.nim(468, 17) Error: undeclared identifier: 'addTimer'`
#### Screenshot
![Screenshot_20210920-225634](https://user-images.githubusercontent.com/26684644/134043793-5f51339d-8906-4770-8e97-42a96c11bb41.png)

#### Other information
It does compile in x86 hardware (in computer) not in aarch64

**Comment by sk-Prime** [comment]
Now it is compiling perfectly.

**Comment by thatrandomperson5** [comment]
> Now it is compiling perfectly.

I am having the same issue, can you go into more detail into how you fixed it? If you truly don’t know or forgot can you at least give a educated guess?
