### ISSUE TITLE
prologue init, broken indentation

### ISSUE THREAD

**Issue by juancarlospaco** [planety/prologue#134]
`logue init` generates code with broken indentation, still works but IDEs complain about it, see warning in red.

![prologue_init](https://user-images.githubusercontent.com/1189414/136535607-d253d374-7f1c-4908-b160-8a9b3fa6e419.png)

It is not 2-space based.

**Comment by juancarlospaco** [comment]
Also an opinion, the code should use `self: Context` ?,
to be consistent with most of the Nim code.

```Nim
proc hello*(ctx: Context) {.async.} =
  resp "<h1>Hello, Prologue!</h1>"
```

to

```Nim
proc hello*(self: Context) {.async.} =
  resp "<h1>Hello, Prologue!</h1>"
```

🤔

**Comment by PhilippMDoerner** [comment]
Made a PR for this in the logue project.
Since this is a trivial fix, assuming it is actually desired, I took the 2 minutes of adjusting the spacing.
Should it not be wanted due to styling preferences, just reject the PR, it doesn't really matter all that much either way ^^'

Here the PR:
https://github.com/planety/logue/pull/2

**Comment by PhilippMDoerner** [comment]
> Also an opinion, the code should use `self: Context` ?, to be consistent with most of the Nim code.
> 
> ```nim
> proc hello*(ctx: Context) {.async.} =
>   resp "<h1>Hello, Prologue!</h1>"
> ```
> 
> to
> 
> ```nim
> proc hello*(self: Context) {.async.} =
>   resp "<h1>Hello, Prologue!</h1>"
> ```
> 
> thinking

Hmmm I'm not sure. Personally I don't like that naming and would prefer for `ctx` to remain named as is. The idea is that you have a handler for the request, so your handler accepts the request context, which contains the request itself and other metadata. The handler is not the request itself, it handles the request. These distinct ideas where what I got from writing prologue for the past 7 months at least.

Changing that to `self` feels like a shift of ideas, as it implies that the handler is that the thing that creates a response is somehow the request itself, which is a confusing mental model, at least to me.

**Comment by ringabout** [comment]
fixed by https://github.com/planety/logue/pull/2
