### ISSUE TITLE
Session object not copied to new context 

### ISSUE THREAD

**Issue by teroz** [planety/prologue#14]
Hey I just tried the blog example and I noticed the session object gets refreshed for every  context ie for every request. i tested by registering a user and logging in with that user and my `userid ` is added to the context's session object on the login handler. 
 When I make another request my session object is empty and I have to log in again. Shouldn't the session object be copied to every new context?

**Comment by xflywind** [comment]
If you want to load and save session, you can use `sessionMiddleware`(it's not well tested).
https://github.com/planety/prologue/blob/a8a423291513c5dced0a457c5c21c9af58127476/src/prologue/middlewares/sessions/signedcookiesession.nim#L17
