### ISSUE TITLE
Typo in `/prologue/security/hashers.nim`

### ISSUE THREAD

**Issue by zr0z** [planety/prologue#140]
Hi,

There is a typo in the hasher signature for `pbkdf2_sha256`.

https://github.com/planety/prologue/blob/0858faa07481740c99e1b38d85db803267dd130e/src/prologue/security/hasher.nim#L32

Should be

```nim
result = fmt"pbkdf2_sha256${salt}${iterations}${output}"
```

The algorithm name is also wrong in `pbkdf2_sha256verify` :

https://github.com/planety/prologue/blob/0858faa07481740c99e1b38d85db803267dd130e/src/prologue/security/hasher.nim#L66

I can create the PR for the fix but it will be a breaking change for people using this hasher, as `pbkdf2_sha256verify` would fail for already stored password digests.

On a side note, in the Python world, [Passlib](https://passlib.readthedocs.io/en/stable/narr/hash-tutorial.html) and [Django](https://docs.djangoproject.com/en/3.2/topics/auth/passwords/#how-django-stores-passwords) are using `pbkdf2_sha256${iterations}${salt}${hash}`, so I was wondering if it would make sense to provide a compatible implementation, in parallel to the existing one.

I can create the necessary PRs if needed.

**Comment by ringabout** [comment]
Hi, thanks for reporting this issue. Since this module is not used internally, maybe we should deprecate this module. Eventually they can be implemented externally.

**Comment by ringabout** [comment]
> so I was wondering if it would make sense to provide a compatible implementation, in parallel to the existing one.

If you want to implement it under the planety organization, I can invite you as a member.

**Comment by zr0z** [comment]
> If you want to implement it under the planety organization, I can invite you as a member.

That's a great offer, thank you very much. Let me think about it!
