### ISSUE TITLE
Can you access the raw HTTP request body?

### ISSUE THREAD

**Issue by PhilippMDoerner** [planety/prologue#143]
Heyho everybody!

I'm currently re-building the backend of a side-project of mine in nim using prologue (Currently: Backend Django - Frontend Angular. I'm planning on replacing Django with Prologue). 

In that side-project I used authentication with JWT. While implementing the typical token refresh mechanism myself, I stumbled over a minor issue. Previously,  to refresh the access token, I sent a POST with a raw request body, containing the refresh-token in a JSON string.  The server grabbed the refresh token from the string from there and did the rest.

The issue I'm running into here is that I'm not sure if Prologue gives you access to the raw request body. 

When I sent a request with a body (e.g. `{"refresh":"<SOME_REFRESH_TOKEN_BASE64_STRING>"}` I found that  `context.request.postParams` and `context.request.formParams` are both empty. Further looking into the [documentation](https://planety.github.io/prologue/context/) I found that the method `getPostParams` and `getFormParams` only supported request bodies of type ` form-urlencoded` and `multipart/form-data`. 

Based on that I assume the raw HTTP request body is parsed and discarded before I can access it in the context. 
Is that correct? 
Or is there a way for me to get that JSON String without having to change how I send that POST request? (It's not a *big* issue for me, but I would prefer it if I could find a way that would avoid it)

If there currently is no way to access that raw HTTP request body, would it be possible to add access to it?

**Comment by PhilippMDoerner** [comment]
The answer is: I am not smart and should read documentation better. I apologize very much for taking up time.

For others stumbling upon this as well: There's a [body](https://planety.github.io/prologue/coreapi/naive/request.html#body%2CRequest)() method to fetch the raw body of an HTTP request

**Comment by mitjafelicijan** [comment]
> The answer is: I am not smart and should read documentation better. I apologize very much for taking up time.
> 
> For others stumbling upon this as well: There's a [body](https://planety.github.io/prologue/coreapi/naive/request.html#body%2CRequest)() method to fetch the raw body of an HTTP request

You could share your solution for others.

The solution for others is `ctx.request.body()`
