### ISSUE TITLE
Streaming file support

### ISSUE THREAD

**Issue by jivank** [planety/prologue#15]
I am wondering if you will drop support for httpbeast for netkit?

I have a pull request that will stream large files, its a simple change but it won't fix the memory leak with httpbeast. Additionally the content-length is sent twice because it appears httpbeast is loading the body data into its own buffer before sending it, so I corrected this with `when defined`, but the content length shows as 0.

On macOS it will serve a 600mb and the executable will use 4.9MB memory afterwards.

Please let me know if you would like me to create a pull request.
`context.nim`
```nim

  else:
    when defined(windows) or defined(usestd):
      ctx.response.setHeader("Content-Length", $contentLength)
    await ctx.respond(Http200, "", headers)
    var
      file = openAsync(filePath, fmRead)

    while true:
      let value = await file.read(4096)
      if value.len > 0:
        await ctx.send(value)
      else:
        break

    file.close()
    ctx.handled = true
```

**Comment by bung87** [comment]
it's acceptable, the use case limit to download file , and set a proper header tell browser

**Comment by xflywind** [comment]
Look at this issue,  I think it should be fixed in httpbeast. 
`asynchttpserver` has the same issue before v1.2.
https://github.com/dom96/jester/issues/241

**Comment by xflywind** [comment]
I think the previous way should work too. Do you have issues with streaming file when you use `asynchttpserver` and the previous way?

**Comment by jivank** [comment]
@xflywind 

Are you referring to
`    when defined(windows) or defined(usestd):`
?

`asynchttpserver` will work without that line. Would you like to me to remove it? I only placed it there so that httpbeast would work but maybe httpbeast already was having an issue.

**Comment by xflywind** [comment]
I mean this:
```nim
  else:
    # TODO stream
    ctx.response.setHeader("Content-Length", $contentLength)
    await ctx.respond(Http200, "", headers)
    var
      fileStream = newFutureStream[string]("staticFileResponse")
      file = openAsync(filePath, fmRead)

    await file.readToStream(fileStream)

    while true:
      let (hasValue, value) = await fileStream.read
      if hasValue:
        await ctx.send(value)
      else:
        break

    file.close()
    ctx.handled = true
```

**Comment by jivank** [comment]
The old method will use ~900MB of memory for the 600MB file. I think this is because readToStream will fully load the file into memory. Also I believe @dom96 mentioned that he needs to rewrite/redesign the streams library.

**Comment by xflywind** [comment]
@jivank 
Alright, pr is welcome. Bur `when defined` is unnecessary because `httpbeast` is broken in sending multiple header fields.

**Comment by bung87** [comment]
close as https://github.com/planety/prologue/pull/16

**Comment by dom96** [comment]
httpbeast could probably benefit from a proc which copies the contents of a file to its fd. There is a POSIX API call for this, if someone wants to implement it I will accept.

Please submit issues for these kinds of things if you haven't already. In particular to the Nim repo since I think the future stream implementation needs fixing.

**Comment by ringabout** [comment]
Yea, when using `asynchttpserver`, the streaming file can work very well. But using `httpx`, it must use blocking read operations to read file. `asyncfile` doesn't work with `httpx`. Reading is blocking!

https://github.com/planety/prologue/blob/4442c4edd5d088032b187edf859df2988733dfc2/src/prologue/core/context.nim#L489

**Comment by ringabout** [comment]
Now `httpx` backend supports streaming file in both windows and unix.
