### ISSUE TITLE
Some characters are not allowed in paths always causes a stacktrace

### ISSUE THREAD

**Issue by mildred** [planety/prologue#182]
I'm having a problem with the error `Illegal characters occurred in the mapped pattern,please restrict to alphanumeric, or the following: - . _ ~ / * { } & '` originating from

https://github.com/planety/prologue/blob/cec75e8089aebe758ec454a6549b13cd638e5bd1/src/prologue/core/route.nim#L132-L133

Is there a specific reason behind this? I wanted to create a service that can handle paths like `/@group/...`. There are other legitimate characters that are not present as well. Is there a specific reason why valid characters in HTTP are forbidden, how can I use them?

I thought initially that was only in the pattern format, but I switched to regex and I still have the issue.

Is there a way to bypass the routing feature in prologue to implement custom routing instead?

**Comment by mildred** [comment]
This also means that anyone can create a stack trace on a prologue server by requesting any URL with a forbidden character, regardless of if the server have a route with this forbidden character on. This does not seem to be a good design I believe.

**Comment by mildred** [comment]
See similar issue in #163 

Reference: https://www.ietf.org/rfc/rfc2396.txt

> The path may consist of a sequence of path segments separated by a single slash "/" character.  Within a path segment, the characters "/", ";", "=", and "?" are reserved.  Each path segment may include a sequence of parameters, indicated by the semicolon ";" character. The parameters are not significant to the parsing of relative references.

That means that in the path part of the URL (before the `?` indicating the query string and after the host part) all characters are allowed except `/` (path delimiters), `;` (path segment parameter), `=` (within the parameter ???) and `?` (start of the query string). Path segment parameters is so rarely used I believe we can skip this. This means that any character can appear except `?` (and `%` reserved for escapes of course).

**Comment by ringabout** [comment]
I agree, it shouldn't check whether the requested path is a valid URL => https://github.com/planety/prologue/blob/cec75e8089aebe758ec454a6549b13cd638e5bd1/src/prologue/core/route.nim#L471

**Comment by ringabout** [comment]
After #183 is merged, you can use regex now

```nim
import prologue

proc hello*(ctx: Context) {.async.} =
  resp "<h1>Hello, Prologue!</h1>"

let app = newApp()
app.get("/", hello)
app.addRoute(re"/@group", hello)
app.run()
```

**Comment by ringabout** [comment]
After https://github.com/planety/prologue/pull/183 is merged, you can use regex route like below
```nim
import prologue

proc hello*(ctx: Context) {.async.} =
  resp "<h1>Hello, Prologue!</h1>"

let app = newApp()
app.get("/", hello)
app.addRoute(re"/@group", hello)
app.run()
```
