### ISSUE TITLE
Cannot serve dynamic websites

### ISSUE THREAD

**Issue by WeebNetsu** [planety/prologue#224]
I was trying to use this library to build my own website. I tried to mix it with Nimja, however, Nimja needs to put data on websites during runtime (which makes sense, since one logged in user will not have the same data as another), however, Prologue seems to want the files as soon as compile time, which is a bit of an issue, since Nimja is during runtime... Is there a way around this, or is this a potential bug or a choice made by the developer? Currently Prologue can only display static content, which is very sad.

**Comment by enthus1ast** [comment]
Nimja compiles your templates on compiletime.

Here is an example for nimja+prologue: https://github.com/enthus1ast/nimja/tree/master/examples/prologue

**Comment by WeebNetsu** [comment]
Oh damn, my mistake! After looking at those examples, I realised where my error was, and it had nothing to do with Prologue or Nimja (just my own stupidity!), sorry for taking your time :')
