### ISSUE TITLE
[Question] Does Context Request includes json body passed to requests?

### ISSUE THREAD

**Issue by naveedhd** [planety/prologue#235]
I am calling a POST request to a route with a request body (json) but the Context does not seem to have the request body or any helper associated to it. 

Am I missing something or is it not implemented yet?

**Comment by mrtlsc** [comment]
This is how you get the json body:
```
import std/json

proc endpoint*(ctx: Context) {.async.} =
  let body = parseJson(ctx.request.body)
```
then let's say the body contains a key "email" with a value of type string, you can get it like this:

`let email = body["email"].getStr()`

**Comment by PhilippMDoerner** [comment]
I have in fact asked myself the same thing a couple years ago and wrote this self answered [SO question](https://stackoverflow.com/questions/70524267/nim-how-to-access-raw-post-request-body-in-prologue-framework) to have sth to google in the future :smile:

**Comment by naveedhd** [comment]
ah right! I was looking at the [request object](https://github.com/planety/prologue/blob/devel/src/prologue/core/beast/request.nim#L13-L22) and missed out on the [body func](https://github.com/planety/prologue/blob/devel/src/prologue/core/beast/request.nim#L61)
