### ISSUE TITLE
Static files inaccessible

### ISSUE THREAD

**Issue by Yakumo-Yukari** [planety/prologue#251]
app.use(staticFileMiddleware("static"))

─ src/
    ├── App.nim
    ├── static/
    │   ├── css/
    │   │   └── style.css
    │   └── js/
    │       └── chat.js

DEBUG GET /css/style.css
DEBUG 404 Not Found {"content-type": @["text/html; charset=UTF-8"]}
DEBUG GET /js/chat.js
DEBUG 404 Not Found {"content-type": @["text/html; charset=UTF-8"]}

**Comment by ringabout** [comment]
When using `staticFileMiddleware`:

- Use the full path of JS, CSS files. For instance, in your HTML file use `templates/some.js` instead of some.js.


See also https://github.com/planety/prologue/pull/131 `staticFileVirtualPathMiddleware`

**Comment by Yakumo-Yukari** [comment]
> When using `staticFileMiddleware`:
> 
> * Use the full path of JS, CSS files. For instance, in your HTML file use `templates/some.js` instead of some.js.
> 
> See also #131 `staticFileVirtualPathMiddleware`

thx
