### ISSUE TITLE
How can I map the path of static files or change the requested file name path?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [planety/prologue#252]
` app.use(staticFileMiddleware("public", "/public")) `
current

http://127.0.0.1:8080/public/uploads/avatars/2_1733822657.jpg

Desired

http://127.0.0.1:8080/uploads/avatars/2_1733822657.jpg

When I need to access avatar images in the `public/uploads/avatars` directory, I currently have to use the full `public/uploads/avatars` path. Is there a way to access it using just the `uploads/avatars/` path, so I don't have to expose the `public` directory?

**Comment by PhilippMDoerner** [comment]
What you generally should be doing either way (as that is very much what they're there for) is *use a reverse proxy* such as nginx, apache and I keep forgetting the name of the new one that is gaining popularity. Such a reverse proxy ideally is always your middle man between HTTP requests from the outside and your prologue application server.

That reverse proxy ideally is also responsible for serving static files such as images, videos and audio files. 

Ideally, prologue is only used for receiving the files and storing them in a dir the reverse proxy can access, not for serving them after the fact.

Therefore what you'd normally be doing is set up some i.e. nginx location rules that maps the url-path "/uploads" to the directory path "/public/uploads/avatars". That rule would likely look remotely something like this:
```
        location /uploads/ {
            #CORS
            add_header Access-Control-Allow-Origin '*';
            add_header Cache-Control 'public, max-age=604800';  # cache for 1 week

            alias /public/uploads/;
        }
```

**Comment by Yakumo-Yukari** [comment]
> What you generally should be doing either way (as that is very much what they're there for) is _use a reverse proxy_ such as nginx, apache and I keep forgetting the name of the new one that is gaining popularity. Such a reverse proxy ideally is always your middle man between HTTP requests from the outside and your prologue application server.
> 
> That reverse proxy ideally is also responsible for serving static files such as images, videos and audio files.
> 
> Ideally, prologue is only used for receiving the files and storing them in a dir the reverse proxy can access, not for serving them after the fact.
> 
> Therefore what you'd normally be doing is set up some i.e. nginx location rules that maps the url-path "/uploads" to the directory path "/public/uploads/avatars". That rule would likely look remotely something like this:
> 
> ```
>         location /uploads/ {
>             #CORS
>             add_header Access-Control-Allow-Origin '*';
>             add_header Cache-Control 'public, max-age=604800';  # cache for 1 week
> 
>             alias /public/uploads/;
>         }
> ```

thx
