### ISSUE TITLE
use "wrk" tool to test it for prologue.

### ISSUE THREAD

**Issue by lihf8515** [planety/prologue#27]
This is a `wrk` test of `httpbeast` `hello word`：wrk -c1000 -d10s http://192.12.1.22:8080/       
                           
Running 10s test @ http://192.12.1.22:8080/
  2 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.01ms   12.16ms 215.10ms   99.05%
    Req/Sec    71.46k     5.27k   76.81k    81.31%
  1407514 requests in 10.05s, 154.37MB read
  Non-2xx or 3xx responses: 1407514
Requests/sec: 140036.79
Transfer/sec:     15.36MB

This is a `wrk` test of `prologue` `hello word`.:wrk -c1000 -d10s http://192.12.1.22:8080/        
                          
Running 10s test @ http://192.12.1.22:8080/
  2 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    34.58ms    0.96ms  39.56ms   78.50%
    Req/Sec    14.51k     1.18k   16.28k    85.35%
  286065 requests in 10.02s, 43.65MB read
Requests/sec:  28538.37
Transfer/sec:      4.35MB

Why is the difference so big？which place cause it so low, suggest to optimize.

**Comment by xflywind** [comment]
I haven't used valgrind to profile it.
But I guess there may exists some aspects which caused its slowness:
1. `httpbeast` uses nil `HttpHeaders` default, `Prologue` uses empty `HttpHeaders` default.
2. `Prologue` uses middlewares which increases overhead.
3. `Prologue` parses query parameters, form parameters and so on.
4. It has `startup`, ` shutdown` event, static file,  to check whether exist.
5. `Prologue` uses logging to print msgs. 
6. Request and Response encapsulation increase overhead.
Also lot of implementation defects will make it slow. I will improve its speed when I have free time.

**Comment by lihf8515** [comment]
Ok! Thank you very much!

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："flywind "<notifications@github.com&gt;;
发送时间：2020年7月1日(星期三) 下午5:42
收件人："planety/prologue" <prologue@noreply.github.com&gt;;
抄送："lihaifeng "<lihaifeng@wxm.com&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [planety/prologue] use "wrk" tool to test it for prologue. (#27)
-----------------------------------

 

 
I haven't used valgrind to profile it.
 But I guess there may exists some aspects which caused its slowness:
  
httpbeast uses nil HttpHeaders default, Prologue uses empty HttpHeaders default.
 
Prologue uses middlewares which increases overhead.
 
Prologue parses query parameters, form parameters and so on.
 
It has startup,  shutdown event, static file,  to check whether exist.
 
Prologue uses logging to print msgs.
 
Request and Response encapsulation increase overhead.
 Also lot of implementation defects will make it slow. I will improve its speed when I have free time.
