### ISSUE TITLE
Documentations and API Reference

### ISSUE THREAD

**Issue by theobouwman** [planety/prologue#3]
Hi,

Where can I find the generated API reference?

On which points do you need help with further development.

I'm asking because this project seems to be the most mature Nam web framework.

**Comment by xflywind** [comment]
Hi, It is far from mature.Because it is only born two months ago.It still lacks a lot of functionality such as Paginator, Hcr(after nim 1.2), graceful shutdown, authentication and so on.When I finish most of functionality, I will begin to finish docs and apis.
Now, it is not ready for use.

**Comment by xflywind** [comment]
If You only need simple api reference. You can use commmand `nim docs` plus single nim file to generate api reference as below.
https://nim-lang.org/docs/docgen.html
Regarding help, I need a better async Nim ecology especially all kinds of async database driver.Now I can only find async mongodb, redis, and pg. I also need http2 server.
I list everything I need below. 
https://github.com/planety/bluePrint/blob/master/task.md 
So it is a heavy work, maybe 1 ~ 2 years, it will be ready for production. :-)
