### ISSUE TITLE
techempower benchmark

### ISSUE THREAD

**Issue by sharkguto** [planety/prologue#30]
first of all I would say nice work !! Your web framework looks great

is it possible you to implement techempower benchs for prologue??? today we have only jester and httpbeast there, and no bench related with any database, like postgresql or mysql.

I confess i am really disappointed with nim, because I can not find any good async driver for access relational databases. Do you have any good to indicate????

**Comment by xflywind** [comment]
Hi, @sharkguto 

Indeed, we don't have any robust async relational database drivers. Most of them are old and don't work.
I think maybe this simple one work. 
https://github.com/treeform/pg

@tulayang is working on a new io model which maybe bring us stable and robust network development kits.  When [netkit](https://github.com/iocrate/netkit) is stable,  `tulayang` or I will work on async database drivers.

So I don't want to benchmark it without robust async ecosystems now.

**Comment by sharkguto** [comment]
> Hi, @sharkguto
> 
> Indeed, we don't have any robust async relational database drivers. Most of them are old and don't work.
> I think maybe this simple one work.
> https://github.com/treeform/pg
> 
> @tulayang is working on a new io model which maybe bring us stable and robust network development kits. When [netkit](https://github.com/iocrate/netkit) is stable, `tulayang` or I will work on async database drivers.
> 
> So I don't want to benchmark it without robust async ecosystems now.

Great news!!! 

I wish success and can't wait for it.
