### ISSUE TITLE
A sleep in one request handler stops other handlers from serving

### ISSUE THREAD

**Issue by jasonprogrammer** [planety/prologue#31]
As mentioned [in this thread on Reddit](https://www.reddit.com/r/nim/comments/gyvzdy/prologue_fullstack_web_framework_written_in_nim/fxbl201/), putting a sleep in one async handler stops another from handling a request. Example code:

```
import os
import prologue
import prologue/middlewares/middlewares


proc home*(ctx: Context) {.async.} =
  resp "<h1>Home</h1>"

proc sleepPage*(ctx: Context) {.async.} =
  sleep(10000)
  resp "<h1>Sleep!</h1>"


let settings = newSettings(appName = "MyApp")
var app = newApp(settings = settings, middlewares = @[debugRequestMiddleware()])
app.addRoute("/", home, @[HttpGet, HttpPost])
app.addRoute("/home", home, HttpGet)
app.addRoute("/sleep", sleepPage, HttpGet)
app.run()
```

If you browse to the `/sleep` page, and then the `/` home page, the loading of the home page will block. If the code is built with threads enabled, the blocking behavior is not present.

**Comment by xflywind** [comment]
Hi, @jasonprogrammer thanks for reporting this issue.

`prologue` use `httpbeast` in linux. But `asyncdispatch` is single-thread. So it maybe block when only use one thread. There is a pending [pr](https://github.com/nim-lang/Nim/pull/12372) to support multithread async. 

Anyway it's bad to use block code in async functions.

**Comment by xflywind** [comment]
I have made a fork version of `httpbeast` which supports `windows` based on [ioselectors](https://github.com/xflywind/ioselectors). When this is ready, I will make `threads:on` default.

**Comment by jasonprogrammer** [comment]
Oh sorry, I should have realized this from the conditional import in `server.nim`. Closing this issue.

As a side note, thanks for all of your work on this framework. I love how the routing works, the documentation and examples are great, and I love that there's a pattern for middleware.
