### ISSUE TITLE
Add listen address / bind interface to settings

### ISSUE THREAD

**Issue by jivank** [planety/prologue#32]
I'd like to be able to specify a custom address for the server. It appears to be set to 0.0.0.0 which means all interfaces will be listened on.

For example, I have a VPS with a public IP but also with private IP (via VPN like wireguard/tinc/zerotier) where I'd like my service not to be exposed to the public. There doesn't seem to be a way to pass the address to `serve*()`.

I'd suggest something like:
```
debug=false # change this
port=8787
appName=HelloWorld
staticDir=/static
secretKey=Pr435ol67ogue
address=0.0.0.0 # or 127.0.0.1 or 10.0.0.1
```

**Comment by xflywind** [comment]
I agree.
