### ISSUE TITLE
Unable to use CSRF middleware

### ISSUE THREAD

**Issue by xbello** [planety/prologue#34]
Maybe I'm doing it wrong.

In my form generation I put the following code (it's a Source Code Filter):

```nim
#? stdtmpl | standard
#import prologue/middlewares/csrf
#
#proc alignForm(ctx: Context): string =                                         
#  result = "" 
<form method="post">
  csrfToken(ctx)
<-- All other inputs -->
</form>
#end proc
```

This fails to create the CSRF token with

```
index 32 not in 0 .. 31
[...]
  /home/xbello/.nimble/pkgs/prologue-0.3.2/prologue/middlewares/csrf.nim(52)     makeToken
  /home/xbello/.choosenim/toolchains/nim-1.2.6/lib/system/fatal.nim(49)          sysFatal
[...]
```

So this traced the index failure to the line 52 in prologue/middlewares/csrf.nim, that is:

`token[idx] = mask[idx] + secret[idx]`

but it turns out that both `mask` and `secret` have a length of 32 elements, as both of them are created with size `
DefaultSecretSize` (32).

I changed the above line to:

`token[idx] = mask[idx - DefaultSecretSize] + secret[idx - DefaultSecretSize]`

And it seems to work now. But I'm no expert in security, so I'm not 100% sure it it makes sense. The CSRF cookie seems to be correctly created and set.

**Comment by xflywind** [comment]
@xbello 
Thanks for reporting this issue!

I think according to this line:
https://github.com/planety/prologue/blob/1d2b10b83d62face945597bc4f07086e3d52aa07/src/prologue/middlewares/csrf.nim#L64

```nim
  for idx in 0 ..< DefaultSecretSize:
    result[idx] = byte(token[idx]) - byte(token[DefaultSecretSize + idx])
```

This should be changed to:
```nim
  for idx in 0 ..< DefaultSecretSize:
    token[idx] = mask[idx] + secret[idx]

  token[DefaultSecretSize ..< DefaultTokenSize] = move mask
```

**Comment by xflywind** [comment]
`Middlewares` is lack of tests, pr is welcome.
