### ISSUE TITLE
Incomplete Blog example (missing routes?)

### ISSUE THREAD

**Issue by keshon** [planety/prologue#35]
I noticed there is no route attached for blog templates in `example/blog`:  http://127.0.0.1:8787/blog/index gives 404.

**Comment by xflywind** [comment]
According to 
https://github.com/planety/prologue/blob/a06925cf982e7ece8cad6411b108b9dc6d71cbbc/examples/blog/app.nim#L17
and 
https://github.com/planety/prologue/blob/a06925cf982e7ece8cad6411b108b9dc6d71cbbc/examples/blog/urls.nim#L7
You should visit `/auth/login` and `/auth/register`.

**Comment by keshon** [comment]
Thanks, but I meant the blog related logic mention here:
https://github.com/planety/prologue/blob/a06925cf982e7ece8cad6411b108b9dc6d71cbbc/examples/blog/templates/indexPage.nim#L12

and here
https://github.com/planety/prologue/blob/a06925cf982e7ece8cad6411b108b9dc6d71cbbc/examples/blog/templates/indexPage.nim#L21

It's not that crucial just confusing that file `templates/indexPage.nim` is not being used anywhere in this example.

**Comment by xflywind** [comment]
This example is not finished, pr is welcome.

**Comment by keshon** [comment]
I'm closing this issue as I considered it solved. It was interesting and educative experience :)
