### ISSUE TITLE
Always asked to install cookiejar when running

### ISSUE THREAD

**Issue by rafmst** [planety/prologue#36]
Hi!
I'm running this on windows, and I always get this request:
![image](https://user-images.githubusercontent.com/924985/91613711-589d2200-e980-11ea-851a-b7616bc71ba1.png)

Anything I should do?

**Comment by xflywind** [comment]
I think it is caused by `cookies` module. I will rename it.

**Comment by xflywind** [comment]
Thanks for reporting this issue. I have fixed it. Please use the latest version.(nimble install prologue@#head)

**Comment by rafmst** [comment]
Worked like a charm :) Thanks for the quick response
