### ISSUE TITLE
Examples - todoapp 404 error

### ISSUE THREAD

**Issue by nixfreak** [planety/prologue#37]
I have noticed that todoapp and todolist both receive a 404 error.  Are these examples still in the works? 

I'm looking for web framework I can use with nim, do you have any other examples you can show that you haven't posted in the repo ? 

`
DEBUG Prologue is serving at 0.0.0.0:8787 
Starting 1 threads
DEBUG GET /
DEBUG 404 Not Found {"content-type": @["text/html; charset=UTF-8"]}
`
Same issue with TodoList 
`
DEBUG Prologue is serving at 0.0.0.0:8787 TodoList
Starting 8 threads
Listening on port 8787
`
<img width="538" alt="Screen Shot 2020-09-10 at 2 16 41 PM" src="https://user-images.githubusercontent.com/3707258/92789486-831faf80-f370-11ea-8d12-62e9c45be56a.png">

**Comment by xflywind** [comment]
https://github.com/planety/prologue/blob/a66699f124f948fe74c4da424dcd4a0aee84afe6/examples/todoapp/app.nim#L14

127.0.0.1 won't work.They both have their own routes. The routes of todoapp is 127.0.0.1/home

**Comment by nixfreak** [comment]
Very cool , thanks got it to work now for todoapp (:

**Comment by xflywind** [comment]
Thanks for your supports!
