### ISSUE TITLE
redis session

### ISSUE THREAD

**Issue by xflywind** [planety/prologue#40]

**Comment by keshon** [comment]
Do you consider making session stored in memory or sqlite support for development purposes?

**Comment by xflywind** [comment]
Session stored in memory for testing is worth considering. Nim doesn't get `memcached` support. So `memcached` is no. `sqlsession` is somewhat terrible in terms of that we do not have stable async relational database driver in Nim. So every database operation is blocking. I don't like database session.

Anyway we already have a session library, users can write their own session middlewares.
https://github.com/FedericoCeratto/nim-httpauth
