### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by UNIcodeX** [planety/prologue#42]
The following code using Prologue gets around 27000 requests per second when tested with `wrk`

```nim
import prologue

let
  # debug attributes must be false
  settings = newSettings(
    appName = "Prologue",
    debug = false,
    port = 8000,
    staticDirs = "static",
    secretKey = ""
  )

proc index*(ctx: Context) {.async.} =
  resp "Welcome!"

var app = newApp(settings = settings)
app.addRoute("/", index)
app.run()
```

Whereas this code for Jester gets around 55000 requests per second.
```nim
import jester

settings:
  port = 8000.Port

routes:
  get "/":
    resp "Welcome!"
```

Both are built and tested with `-d:release -d:danger` flags.

I'm evaluating frameworks for use in a production app. The more efficient the better for this use case. Any insight on how to improve performance with Prologue?

**Comment by xflywind** [comment]
what's your platform? Could you test both with `--threads:on`?

**Comment by UNIcodeX** [comment]
sure, but I am unable to use threading currently, because anonimongo has an issue converting bson to json due to not being thread-safe when trying to use `--threads:on`. I added `--gc:markAndSweep` because it seems to squeeze out a bit more performance.

Prologue `nim c -r -d:release -d:danger --threads:on --gc:markAndSweep`
```
$ curl http://localhost:8000 && echo "\n" && wrk -t15 -c250 -d5s http://localhost:8000
Welcome!

Running 5s test @ http://localhost:8000
  15 threads and 250 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.67ms    6.15ms 131.86ms   91.11%
    Req/Sec     4.54k     1.55k   12.87k    73.13%
  339430 requests in 5.09s, 45.97MB read
Requests/sec:  66750.69
Transfer/sec:      9.04MB
```

Jester `nim c -r -d:release -d:danger --threads:on --gc:markAndSweep`
```
$ curl http://localhost:8000 && echo "\n" && wrk -t15 -c250 -d5s http://localhost:8000
Welcome!

Running 5s test @ http://localhost:8000
  15 threads and 250 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.10ms    4.30ms  61.02ms   90.01%
    Req/Sec     7.40k     2.48k   28.35k    72.24%
  556997 requests in 5.10s, 74.90MB read
Requests/sec: 109244.08
Transfer/sec:     14.69MB

```

**Comment by xflywind** [comment]
Sorry for this result. But I have no good idea to make prologue faster right now.
You can use `jester` for production.
