### ISSUE TITLE
Differences with Jester

### ISSUE THREAD

**Issue by kidandcat** [planety/prologue#6]
What are the differences with Jester?

**Comment by xflywind** [comment]
Jester is mature and prodiction-ready.But Prologue is still young and isn't finished.

Jester is flexible.Jester provides basic tools to process request and response.You can use everything else you like for example httpauth and so on.Prologue decides much more things for you.It is like django.From security to form validation, Prologue intends to supply best practises.Of course, you can also use your own modules.

Jester is powerful.Jester provides power macros to help you enjoy your life.It is easy to use and reduces duplicated codes.Prologue is no magic.It intends to use normal procs and provides no surprise for users.
