### ISSUE TITLE
jsonResponse -- "application/json"

### ISSUE THREAD

**Issue by UNIcodeX** [planety/prologue#67]
Why does the code in `prologue/core/response` refer to `## Content-Type: application/json`, but then actually return a Content-Type of `text/json`?

```nim
func jsonResponse*(text: JsonNode, code = Http200, headers = newHttpHeaders(),
                   version = HttpVer11): Response {.inline.} =
  ## Content-Type: application/json.
  result = initResponse(version, code, headers, body = $text)
  if unlikely(result.headers == nil):
    result.headers = newHttpHeaders()
  result.headers["Content-Type"] = "text/json"
```

**Comment by ringabout** [comment]
It should be `application/json`. I made a mistake. Thanks for reporting this issue.  Feel free to make a pr.

**Comment by UNIcodeX** [comment]
done. https://github.com/planety/prologue/pull/76
