### ISSUE TITLE
do not hijack poll loop

### ISSUE THREAD

**Issue by enthus1ast** [planety/prologue#68]
currently app.run calls `waitFor` to drive async handlers.
This prevents user to run other async code.
My proposal is to give users the option to drive their own async poll loop.

This is not possible right now:

```nim

# app.nim
import prologue


proc hello*(ctx: Context) {.async.} =
  resp "<h1>Hello, Prologue!</h1>"

proc someOtherAsyncWork() {.async.} =
  while true:
    echo "some other async work"
    await sleepAsync(1_000)

let settings = newSettings()
var app = newApp(settings = settings)
app.addRoute("/", hello)
asyncCheck someOtherAsyncWork()
app.run()

```

I think something like this should be possible:

```nim 
# app.nim
import prologue


proc hello*(ctx: Context) {.async.} =
  resp "<h1>Hello, Prologue!</h1>"

proc someOtherAsyncWork() {.async.} =
  while true:
    echo "some other async work"
    await sleepAsync(1_000)

let settings = newSettings()
var app = newApp(settings = settings)
app.addRoute("/", hello)
asyncCheck someOtherAsyncWork()
waitFor app.runAsync() # maybe introduce runAsync? or make `run` multisync?
```

**Comment by ringabout** [comment]
hi @enthus1ast

It may be not the fault of `waitFor`. It works if using `asynchttpserver`(-d:usestd). But it doesn't work with [httpx](https://github.com/xflywind/httpx)(the fork of httpbeast). It maybe needs some hacks into `httpx`.

Prologue supports two Http servers(will be three soon):
https://github.com/planety/prologue/tree/devel/src/prologue/core/beast
https://github.com/planety/prologue/tree/devel/src/prologue/core/naive

**Comment by enthus1ast** [comment]
thank you @xflywind for my small usecase `-d:usestd` will be enough.

**Comment by ringabout** [comment]
Yea, it only happens in windows with `httpx`.

**Comment by ringabout** [comment]
`prologue` will only use `asynchttpserver` for the time being.
This works in unix with `httpx`.

**Comment by ringabout** [comment]
It is the bug of `httpx`, I have fixed it in windows. So it works fine with `httpx` in windows and linux.
