### ISSUE TITLE
Http404 ignores body string and sends default message

### ISSUE THREAD

**Issue by enthus1ast** [planety/prologue#69]
```nim
resp("my response on 404", Http404)
```
sends the default build in error message, instead of the supplied body string.

maybe the default could be send when a body is omitted:

```nim
resp(Http404)
```

**Comment by xflywind** [comment]
You can use your own error handler

**Comment by ringabout** [comment]
https://planety.github.io/prologue/coreapi/application.html#registerErrorHandler%2CPrologue%2CopenArray%5BHttpCode%5D%2CErrorHandler


Prologue uses default error handler for http404 and http500. If you doesn't need this behaviour, you could change it in `newApp`.


for example `newApp(errorhandler=newErrorHandler()`

**Comment by ringabout** [comment]
'If you have any question, you could contact me in discord(link in readme)

**Comment by enthus1ast** [comment]
unfortunately there is no `newErrorHandler()` function (at least in the 0.3.6).
There is:

```nim
var app = newApp(settings = settings, errorHandlerTable=newErrorHandlerTable())
```

But i when i remove the default error handler, then routes to unavailable static files, would also be affected.

Wouldn't it be nice to have both behaviors? Leave the default handler in place, but when a user decided to send a custom error, just deliver it?

What do you think about this behavior?

send default error:
```nim
resp(Http404)
```

send string in body:
```nim
resp("my error for this specific route", Http404)
```

because currently the explicitly given error message ist silently omitted.

**Comment by ringabout** [comment]
In prologue 0.3.6  set `ctx.handled = true`  to bypass the default error handler.
Notes that it will discard following middlewares.

Workaround:
```nim
proc hello(ctx: Context) =
  if error:
    ctx.request.respond(Http404, "my error for this specific route")
    ctx.handled = true
```
Your idea is great, but I'm preparing the next big features releases(contains some breaking changes), will consider it.

**Comment by ringabout** [comment]
`resp("my response on 404", Http404)` now will send user-defined error msgs.
You can `respDefault` to respond default msgs.
https://github.com/planety/prologue/blob/37b577c5d5037c24ddea15d3a1444cb8fa166c7d/tests/mocking/t_errorhandler.nim#L16
