### ISSUE TITLE
add `getFormParam` for convenience

### ISSUE THREAD

**Issue by enthus1ast** [planety/prologue#70]
there is a `getPostParam` which is nice, 
but when uploading a file with a post, and the form enctype is changed to ` "multipart/form-data"`
one must use this long inconvenient code `ctx.request.formParams.data[key].body`, to access the formerly post params.

For such a case maybe consider adding a:

```nim
template getFormParam(ctx: Context, key: string): string =
  ctx.request.formParams.data[key].body
```

**Comment by ringabout** [comment]
prologue has provides `getUploadFile` for this goal.

https://planety.github.io/prologue/coreapi/context.html#getUploadFile%2CContext%2Cstring

https://planety.github.io/prologue/uploadfile/

Maybe you can contact me in https://discord.gg/e2dB4WT

**Comment by enthus1ast** [comment]
`getUploadFile` expects the key "file.params["filename"]", but these are not set when just posting normal form data.

**Comment by ringabout** [comment]
Feel free to make a pr
```nim
func getFormParams(ctx: Context; key: string; default = ""): string {.inline.}
```
