### ISSUE TITLE
maxBody cannot be specified

### ISSUE THREAD

**Issue by enthus1ast** [planety/prologue#74]
`asyncHttpServer` has a maxBody parameter, this cannot be specified when running prologue app (not sure if other backends also have such a parameter). Larger file uploads results in: `413 Request Entity Too Large`

**Comment by ringabout** [comment]
Maybe this can be done by a middleware?

**Comment by maksimka221** [comment]
norm

**Comment by ringabout** [comment]
Now `Prologue` supports that `asynchttpserver` backend specifies the `maxBody` parameter. Other backend should use `nginx` to implement this function.

Example(-d:usestd):
```nim
let settings = newSettings(port = Port(8080), data = %* {"maxBody": 1000})
var app = newApp(settings, middlewares = @[debugRequestMiddleware()])
app.addRoute("/upload", upload, @[HttpGet, HttpPost])
app.run()
```

**Comment by enthus1ast** [comment]
are you sure you wanna use json for the settings?
It might be better to give settings a maxBody attribute, and warn the user and ignore settings 
which are not implemented for a specific backend. (--> less magic)

**Comment by ringabout** [comment]
I don't like the option which doesn't work. We can't put everything to the attributes of `settings`. If `maxBody` is supported by all backends, it maybe in the form of attributes. By this way, we can support as many as settings of different server settings. Some name collision may happen, we can use prefix to solve this problem: for example `stdlib_maxBody`, or provides a function automatically generates this name, `getName("maxBody") => stdlib_maxBody`. If settings is non-existing in some backends,  raise exception in compile time. 

And we can do better by writing docs for different servers.
