### ISSUE TITLE
ApacheBench timesout on prologue hello world

### ISSUE THREAD

**Issue by 0atman** [planety/prologue#9]
First time trying Prologue, so I give it a quick bench to see how web scale (:laughing:) it is, and I trip up immediately: 

```shell
$ ab localhost:8080/
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/
Benchmarking localhost (be patient)...

apr_pollset_poll: The timeout specified has expired (70007)
```
Looking at the output, prologue recieves exactly ONE request:

```sql
DEBUG GET /
DEBUG 200 OK {"content-type": @["text/html; charset=UTF-8"]}
```
and then no more.

Here's the code, unmodified from the docs:
```nim
import prologue

proc hello*(ctx: Context) {.async.} =
  resp "<h1>Hello, Prologue!</h1>"

let settings = newSettings()
var app = newApp(settings = settings)
app.addRoute("/", hello)
app.run()
```

Which I compiled simply as a release binary:
```shell
$ nim c -d:release pl.nim
```

What's up?

**Comment by 0atman** [comment]
For the avoidance of doubt, I have benchmarked a few things with this install of ApacheBench, so I imagine my install works. Ubuntu 19.10

**Comment by 0atman** [comment]
also:
```
 λ nimble --version
nimble v0.11.0 compiled at 2020-01-23 17:15:42
git hash: couldn't determine git hash

 λ nim --version
Nim Compiler Version 1.0.6 [Linux: amd64]
Compiled at 2020-01-23
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by xflywind** [comment]
First, please don't use localhost, use really ip instead and specify numbers of `requests`.

Second, if you want to bench prologue with `httpbeast`, please use `nginx` as  reverse proxy.

Third, you can use directly test prologue with `-d:usestd`[asynchttpserver] which is slower than `httpbeast` but works.

```
nim c -r --d:release -d:usestd app.nim
ab -n 5000 realip/login
```

some results

**Comment by 0atman** [comment]
that works! Thank you!
