### ISSUE TITLE
What are the issues with asynchttpserver?

### ISSUE THREAD

**Issue by rishavs** [planety/prologue#90]
Hi

I noticed that the doc for asynchttpserver says;

This HTTP server has not been designed to be used in production, but for testing applications locally. Because of this, when deploying your application you should use a reverse proxy (for example nginx) instead of allowing users to connect directly to this server.

I was wondering what are the issues with asynchttpserver, that the nim maintainers consider it not fit for production?

Also, considering that prologue is built on top of this server, how is prologue planning to tackle these issues?

**Comment by ringabout** [comment]
The default server of Prologue is httpx which is a cross platform HTTP server and faster than asynchttpserver. 
 The description is bit confusied for nee users. It means that asynchttpserver is not production ready without nginx. If used with nginx, it is prodiction ready. So does httpx.

**Comment by rishavs** [comment]
So, as long as we use a reverse proxy like nginx, or a service like cloudflare to act as the endpoint, it should be fine?
Sounds good. I will close the issue.
